spring:
  application:
    name: Todo
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:todo_dev}
    username: ${POSTGRES_USERNAME:todo_dev}
    password: ${POSTGRES_PASSWORD:todo_dev12345}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
