CREATE TABLE IF NOT EXISTS todo_list (
    id          INT UNIQUE GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT                                 NOT NULL,
    description TEXT
);

INSERT INTO todo_list VALUES (1, 'Default', 'This is the default list to capture any existing todos.');

ALTER TABLE todo
ADD COLUMN list_id INT NOT NULL DEFAULT 1,
ADD CONSTRAINT pk_todo_list_todos FOREIGN KEY (list_id) REFERENCES todo_list (id);
