CREATE TABLE todo
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT                                 NOT NULL,
    description TEXT,
    points      INT,
    assignee    TEXT
);

INSERT INTO todo (name, description) VALUES
('Test todo', 'This is our first todo');